DROP TABLE IF EXISTS TRANSPORTISTAS;
DROP TABLE IF EXISTS DADORES_DE_CARGAS;
DROP TABLE IF EXISTS PEDIDOS;
DROP TABLE IF EXISTS IMAGENES;
DROP TABLE IF EXISTS TIPOS_CARGAS;
DROP TABLE IF EXISTS LOCALIDADES;
DROP TABLE IF EXISTS PROVINCIAS;
DROP TABLE IF EXISTS DOMICILIOS;
DROP TABLE IF EXISTS TRANSPORTISTAS_X_LOCALIDAD;

CREATE TABLE TRANSPORTISTAS (
    ID_TRANSPORTISTAS INTEGER
        constraint PK_ID_TRANSPORTISTAS
            primary key autoincrement,
    NOMBRE TEXT,
    APELLIDO TEXT,
    EMAIL TEXT DEFAULT 'tango.app.grupo10@gmail.com',
    VEHICULO TEXT,
    CBU INTEGER
);

CREATE TABLE TRANSPORTISTAS_X_LOCALIDAD (
    ID_TRANSPORTISTAS INTEGER,
    ID_LOCALIDAD INTEGER,
    CONSTRAINT PK_TRANSPORTISTAS_X_LOCALIDAD PRIMARY KEY (ID_TRANSPORTISTAS, ID_LOCALIDAD),
    CONSTRAINT FK_ID_TRANSPORTISTAS FOREIGN KEY (ID_TRANSPORTISTAS) REFERENCES TRANSPORTISTAS(ID_TRANSPORTISTAS),
    CONSTRAINT FK_ID_LOCALIDAD FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDADES(ID_LOCALIDAD)
);

CREATE TABLE DOMICILIOS
(
    ID_DOMICILIO INTEGER PRIMARY KEY AUTOINCREMENT,
    CALLE TEXT NOT NULL,
    ALTURA INTEGER DEFAULT 'S/N',
    PISO INTEGER,
    DEPTO TEXT,
    REFERENCIA TEXT,
    ID_LOCALIDAD INTEGER NOT NULL,
    CONSTRAINT FK_ID_LOCALIDAD FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDADES(ID_LOCALIDAD)
);

CREATE TABLE LOCALIDADES(
    ID_LOCALIDAD INTEGER
        constraint PK_ID_LOCALIDAD
            primary key,
    ID_PROVINCIA INTEGER  NOT NULL,
    NOMBRE TEXT,
    CONSTRAINT FK_ID_PROVINCIAS FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIAS(ID_PROVINCIA)
);


CREATE TABLE PROVINCIAS(
    ID_PROVINCIA INTEGER constraint PK_ID_PROVINCIAS
            primary key,
    NOMBRE TEXT
);

CREATE TABLE DADORES_DE_CARGAS (
    ID_DADOR INTEGER
        constraint PK_ID_DADOR
            primary key autoincrement,
    NOMBRE TEXT NOT NULL,
    APELLIDO TEXT NOT NULL,
    DOMILICILIO TEXT  NOT NULL,
    CONSTRAINT FK_TIPOS_DOMICILIOS FOREIGN KEY (DOMILICILIO) REFERENCES DOMICILIOS(ID_DOMICILIO)
);

CREATE TABLE PEDIDOS (
    NUM_PEDIDOS INTEGER
        constraint PK_NUM_PEDIDOS
            primary key autoincrement,
    OBSERVACIONES TEXT,
    FEC_ENTREGA DATE NOT NULL,
    FEC_RETIRO DATE NOT NULL,
    TIPO_CARGA INTEGER  NOT NULL,
    ID_DADOR TEXT  NOT NULL,
    COTIZACION INTEGER,
    CONSTRAINT FK_TIPOS_CARGAS FOREIGN KEY (TIPO_CARGA) REFERENCES TIPOS_CARGAS(ID_TIPO_CARGA),
    CONSTRAINT FK_DADORES FOREIGN KEY (ID_DADOR) REFERENCES DADORES_DE_CARGAS(ID_DADOR)
);

CREATE TABLE IMAGENES (
    ID_IMAGENES INTEGER PRIMARY KEY AUTOINCREMENT,
    NUM_PEDIDO INTEGER  NOT NULL,
    CONSTRAINT FK_NUM_PEDIDOS FOREIGN KEY (NUM_PEDIDO)   REFERENCES PEDIDOS(NUM_PEDIDOS)
);

CREATE TABLE  TIPOS_CARGAS (
    ID_TIPO_CARGA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT
);