version: "3.9"
services:
  tango-app-api:
    image: tango-app-api
    container_name: tango-app-api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - tango-app-email-server

  tango-app-email-server:
    image: tango-app-email-server
    container_name: tango-app-email-server
    ports:
      - "8082:8082"
    networks:
      - spring-network
networks:
  spring-network: